Traceback (most recent call last):
  File "/usr/local/bin/regsnp_intron", line 4, in <module>
    __import__('pkg_resources').run_script('regsnp-intron==0.1.6', 'regsnp_intron')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/regsnp_intron-0.1.6-py2.7.egg/EGG-INFO/scripts/regsnp_intron", line 10, in <module>
    
  File "build/bdist.linux-x86_64/egg/regsnp_intron/feature_calculator.py", line 23, in <module>
  File "build/bdist.linux-x86_64/egg/regsnp_intron/conservation/phylop.py", line 6, in <module>
  File "lib/bx/bbi/bigwig_file.pyx", line 1, in init bx.bbi.bigwig_file
  File "__init__.pxd", line 918, in init bx.bbi.bbi_file
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
